"""Lightweight services for Tech Cartography v9."""

from .demo_data import load_demo_signals, load_demo_watch_profile
from .digest_export import build_weekly_digest_markdown, signals_to_csv, signals_to_json
from .persistence import (
  ensure_v9_run_dirs,
  get_v9_runs_dir,
  list_snapshots,
  load_snapshot,
  load_watch_profile,
  save_digest_files,
  save_snapshot,
  save_watch_profile,
)
from .query_preview import (
  build_company_query_preview,
  build_paper_query_preview,
  build_patent_query_preview,
  build_query_preview_bundle,
  build_web_query_preview,
)
from .review_state import (
  REVIEW_DECISIONS,
  REVIEW_PRIORITIES,
  apply_review_to_signal,
  apply_reviews_to_signals,
  default_review_state,
  normalize_review_decision,
  normalize_review_priority,
  normalize_review_state,
  sort_signals_by_review,
  summarize_reviews,
)
from .signal_loader import (
  enrich_signals_with_profile,
  load_signals_from_csv_text,
  load_signals_from_json_text,
  normalize_signal_record,
  normalize_signal_records,
  prepare_uploaded_signals,
  score_signal_with_profile,
)
from .score_explainer import (
  attach_score_explanations,
  build_signal_text_blob,
  explain_action,
  explain_signal_score,
  find_keyword_hits,
)
from .signal_template import build_csv_template, build_json_template
from .signal_models import Signal, WatchProfile
from .signal_scoring import (
  apply_watch_profile_suggestions,
  classify_action,
  classify_status,
  select_diverse_top_signals,
)
from .snapshot_diff import apply_snapshot_status, compare_snapshots
from .watch_profile_schema import (
  build_profile_from_form,
  default_bilingual_watch_profile,
  migrate_watch_profile,
  normalize_publication_number,
  normalize_terms,
  parse_publication_numbers,
  parse_terms,
  split_terms,
  watch_profile_summary,
)

__all__ = [
  "Signal",
  "WatchProfile",
  "REVIEW_DECISIONS",
  "REVIEW_PRIORITIES",
  "apply_snapshot_status",
  "apply_watch_profile_suggestions",
  "apply_review_to_signal",
  "apply_reviews_to_signals",
  "attach_score_explanations",
  "build_signal_text_blob",
  "build_weekly_digest_markdown",
  "build_company_query_preview",
  "build_csv_template",
  "build_json_template",
  "build_paper_query_preview",
  "build_patent_query_preview",
  "build_profile_from_form",
  "build_query_preview_bundle",
  "build_web_query_preview",
  "classify_action",
  "classify_status",
  "compare_snapshots",
  "default_bilingual_watch_profile",
  "default_review_state",
  "ensure_v9_run_dirs",
  "enrich_signals_with_profile",
  "explain_action",
  "explain_signal_score",
  "find_keyword_hits",
  "get_v9_runs_dir",
  "list_snapshots",
  "load_demo_signals",
  "load_demo_watch_profile",
  "load_signals_from_csv_text",
  "load_signals_from_json_text",
  "load_snapshot",
  "load_watch_profile",
  "migrate_watch_profile",
  "normalize_publication_number",
  "normalize_review_decision",
  "normalize_review_priority",
  "normalize_review_state",
  "normalize_terms",
  "normalize_signal_record",
  "normalize_signal_records",
  "parse_publication_numbers",
  "parse_terms",
  "prepare_uploaded_signals",
  "score_signal_with_profile",
  "select_diverse_top_signals",
  "save_digest_files",
  "save_snapshot",
  "save_watch_profile",
  "sort_signals_by_review",
  "signals_to_csv",
  "signals_to_json",
  "split_terms",
  "summarize_reviews",
  "watch_profile_summary",
]
