"""Lightweight services for Tech Cartography v9.

This package intentionally avoids eager provider imports so plain
`streamlit run app.py` works without requiring `PYTHONPATH=.:src`.
"""

from __future__ import annotations

from importlib import import_module

_MODULE_EXPORTS: dict[str, list[str]] = {
  ".demo_data": [
    "load_demo_signals",
    "load_demo_watch_profile",
  ],
  ".digest_export": [
    "build_weekly_digest_markdown",
    "signals_to_csv",
    "signals_to_json",
  ],
  ".email_delivery": [
    "EMAIL_SCHEMA_VERSION",
    "EMAIL_SEND_MODE_PREVIEW",
    "EMAIL_SEND_MODE_SELF_ONLY",
    "EmailDeliveryConfig",
    "build_digest_email_preview",
    "build_digest_email_subject",
    "load_email_delivery_config",
    "run_email_delivery_dry_run",
    "save_email_delivery_log",
    "send_digest_email_self_only",
    "validate_self_only_delivery",
  ],
  ".weekly_run_config": [
    "DEFAULT_WATCH_PROFILE_PATH",
    "VALID_EMAIL_MODES",
    "VALID_WEEKDAYS",
    "WEEKLY_RUN_CONFIG_SCHEMA_VERSION",
    "default_weekly_run_config",
    "load_weekly_run_config",
    "resolve_project_path",
    "sanitize_weekly_run_config",
    "validate_weekly_run_config",
  ],
  ".weekly_scheduler": [
    "SUCCESSFUL_WEEKLY_STATUSES",
    "TERMINAL_WEEKLY_STATUSES",
    "WEEKLY_SCHEDULER_SCHEMA_VERSION",
    "WEEKLY_STAGE_SEQUENCE",
    "acquire_weekly_run_lock",
    "build_cron_preview",
    "build_launchd_preview",
    "find_previous_successful_weekly_run",
    "release_weekly_run_lock",
    "run_weekly_watch",
  ],
  ".persistence": [
    "ensure_v9_run_dirs",
    "get_v9_runs_dir",
    "list_snapshots",
    "load_snapshot",
    "load_watch_profile",
    "save_digest_files",
    "save_snapshot",
    "save_watch_profile",
  ],
  ".patent_bigquery_query": [
    "FORBIDDEN_SQL_TOKENS",
    "PUBLICATIONS_TABLE",
    "build_patent_candidates_csv",
    "build_patent_bigquery_preview",
    "build_patent_bigquery_sql",
    "build_patent_query_parameters",
    "build_patent_validation_csv",
    "execute_patent_bigquery_retrieval",
    "run_patent_bigquery_dry_run",
    "save_patent_dry_run_artifacts",
    "save_patent_retrieval_artifacts",
    "validate_patent_bigquery_request",
  ],
  ".paper_openalex_retrieval": [
    "OPENALEX_WORKS_API",
    "SEMANTIC_SCHOLAR_FALLBACK_INTERFACE",
    "build_openalex_paper_candidates_csv",
    "build_openalex_paper_preview",
    "build_openalex_search_url",
    "build_openalex_validation_csv",
    "execute_openalex_paper_retrieval",
    "save_openalex_paper_retrieval_artifacts",
    "validate_openalex_request",
  ],
  ".web_company_retrieval": [
    "CONTENT_ACCESS_VALUES",
    "DEFAULT_SUMMARY_TOP_N",
    "DEFAULT_VERIFICATION_LIMIT",
    "DISCOVERY_SHORTAGE_THRESHOLD",
    "PROVIDER_GOOGLE_GROUNDING",
    "PROVIDER_TAVILY",
    "build_global_web_retrieval_preview",
    "build_web_company_candidates_csv",
    "execute_global_web_retrieval",
    "save_global_web_retrieval_artifacts",
    "validate_global_web_retrieval_request",
  ],
  ".query_preview": [
    "build_company_query_preview",
    "build_paper_query_preview",
    "build_patent_query_preview",
    "build_query_preview_bundle",
    "build_web_query_preview",
  ],
  ".global_web_plan": [
    "build_global_web_country_coverage",
    "build_global_web_plan_validation_rows",
    "build_global_web_search_plan",
    "summarize_global_web_search_plan_ja",
    "validate_global_web_search_plan",
  ],
  ".global_web_plan_export": [
    "build_global_web_country_coverage_csv",
    "build_global_web_search_plan_csv",
    "build_global_web_search_plan_markdown",
    "build_global_web_validation_csv",
    "export_global_web_search_plan",
  ],
  ".global_web_plan_schema": [
    "COUNTRY_PROFILES_PATH",
    "DEFAULT_GLOBAL_WEB_COUNTRY_CODES",
    "DEFAULT_GLOBAL_WEB_INTENTS",
    "GLOBAL_WEB_PLAN_SCHEMA_VERSION",
    "build_country_profile_map",
    "load_global_web_country_profiles",
    "validate_country_profiles",
  ],
  ".review_state": [
    "REVIEW_DECISIONS",
    "REVIEW_PRIORITIES",
    "apply_review_to_signal",
    "apply_reviews_to_signals",
    "default_review_state",
    "normalize_review_decision",
    "normalize_review_priority",
    "normalize_review_state",
    "sort_signals_by_review",
    "summarize_reviews",
  ],
  ".retrieval_run_store": [
    "RETRIEVAL_MANIFEST_SCHEMA_VERSION",
    "build_retrieval_run_manifest",
    "build_theme_id",
    "discover_retrieval_runs",
    "find_latest_compatible_manifest",
    "load_candidates_from_manifest",
    "load_paper_retrieval_artifact",
    "load_patent_retrieval_artifact",
    "load_retrieval_run_manifest",
    "load_web_company_retrieval_artifact",
    "save_retrieval_run_manifest",
    "stable_payload_signature",
  ],
  ".search_plan": [
    "DEFAULT_SOURCE_LIMITS",
    "DEFAULT_TOTAL_LIMIT",
    "batch_terms",
    "build_company_search_plan",
    "build_paper_search_plan",
    "build_patent_search_plan",
    "build_unified_search_plan",
    "build_web_search_plan",
    "normalize_source_limits",
    "normalize_total_limit",
    "summarize_search_plan_ja",
    "validate_search_plan",
  ],
  ".signal_loader": [
    "enrich_signals_with_profile",
    "load_signals_from_csv_text",
    "load_signals_from_json_text",
    "normalize_signal_record",
    "normalize_signal_records",
    "prepare_uploaded_signals",
    "score_signal_with_profile",
  ],
  ".signal_integration": [
    "apply_signal_change_tracking",
    "build_source_top_signals",
    "deduplicate_signal_candidates",
    "integrate_multi_source_signals",
    "rank_integrated_signals",
  ],
  ".score_explainer": [
    "attach_score_explanations",
    "build_signal_text_blob",
    "explain_action",
    "explain_signal_score",
    "find_keyword_hits",
  ],
  ".signal_template": [
    "build_csv_template",
    "build_json_template",
  ],
  ".signal_models": [
    "Signal",
    "WatchProfile",
  ],
  ".signal_scoring": [
    "apply_watch_profile_suggestions",
    "classify_action",
    "classify_status",
    "select_diverse_top_signals",
  ],
  ".snapshot_diff": [
    "apply_snapshot_status",
    "compare_snapshots",
  ],
  ".watch_profile_schema": [
    "build_profile_from_form",
    "default_bilingual_watch_profile",
    "migrate_watch_profile",
    "normalize_publication_number",
    "normalize_terms",
    "parse_publication_numbers",
    "parse_terms",
    "split_terms",
    "watch_profile_summary",
  ],
}

_EXPORTS = {
  name: module_path
  for module_path, names in _MODULE_EXPORTS.items()
  for name in names
}

__all__ = [
  "Signal",
  "WatchProfile",
  "REVIEW_DECISIONS",
  "REVIEW_PRIORITIES",
  "CONTENT_ACCESS_VALUES",
  "DEFAULT_SOURCE_LIMITS",
  "DEFAULT_SUMMARY_TOP_N",
  "DEFAULT_TOTAL_LIMIT",
  "DEFAULT_VERIFICATION_LIMIT",
  "DISCOVERY_SHORTAGE_THRESHOLD",
  "FORBIDDEN_SQL_TOKENS",
  "OPENALEX_WORKS_API",
  "PROVIDER_GOOGLE_GROUNDING",
  "PROVIDER_TAVILY",
  "PUBLICATIONS_TABLE",
  "RETRIEVAL_MANIFEST_SCHEMA_VERSION",
  "SEMANTIC_SCHOLAR_FALLBACK_INTERFACE",
  "COUNTRY_PROFILES_PATH",
  "DEFAULT_GLOBAL_WEB_COUNTRY_CODES",
  "DEFAULT_GLOBAL_WEB_INTENTS",
  "GLOBAL_WEB_PLAN_SCHEMA_VERSION",
  "DEFAULT_WATCH_PROFILE_PATH",
  "EMAIL_SCHEMA_VERSION",
  "EMAIL_SEND_MODE_PREVIEW",
  "EMAIL_SEND_MODE_SELF_ONLY",
  "EmailDeliveryConfig",
  "SUCCESSFUL_WEEKLY_STATUSES",
  "TERMINAL_WEEKLY_STATUSES",
  "VALID_EMAIL_MODES",
  "VALID_WEEKDAYS",
  "WEEKLY_RUN_CONFIG_SCHEMA_VERSION",
  "WEEKLY_SCHEDULER_SCHEMA_VERSION",
  "WEEKLY_STAGE_SEQUENCE",
  "apply_snapshot_status",
  "apply_signal_change_tracking",
  "apply_watch_profile_suggestions",
  "apply_review_to_signal",
  "apply_reviews_to_signals",
  "attach_score_explanations",
  "batch_terms",
  "build_country_profile_map",
  "build_global_web_country_coverage",
  "build_global_web_country_coverage_csv",
  "build_global_web_plan_validation_rows",
  "build_global_web_retrieval_preview",
  "build_global_web_search_plan",
  "build_global_web_search_plan_csv",
  "build_global_web_search_plan_markdown",
  "build_global_web_validation_csv",
  "build_cron_preview",
  "build_launchd_preview",
  "build_signal_text_blob",
  "build_source_top_signals",
  "build_weekly_digest_markdown",
  "build_digest_email_preview",
  "build_digest_email_subject",
  "build_company_query_preview",
  "build_company_search_plan",
  "build_csv_template",
  "build_json_template",
  "build_openalex_paper_candidates_csv",
  "build_openalex_paper_preview",
  "build_openalex_search_url",
  "build_openalex_validation_csv",
  "build_patent_bigquery_preview",
  "build_patent_bigquery_sql",
  "build_patent_candidates_csv",
  "build_patent_query_parameters",
  "build_patent_validation_csv",
  "build_paper_query_preview",
  "build_paper_search_plan",
  "build_patent_query_preview",
  "build_patent_search_plan",
  "build_profile_from_form",
  "build_query_preview_bundle",
  "build_retrieval_run_manifest",
  "build_theme_id",
  "build_unified_search_plan",
  "build_web_query_preview",
  "build_web_search_plan",
  "build_web_company_candidates_csv",
  "classify_action",
  "classify_status",
  "compare_snapshots",
  "default_bilingual_watch_profile",
  "default_weekly_run_config",
  "default_review_state",
  "deduplicate_signal_candidates",
  "discover_retrieval_runs",
  "ensure_v9_run_dirs",
  "enrich_signals_with_profile",
  "execute_global_web_retrieval",
  "execute_openalex_paper_retrieval",
  "execute_patent_bigquery_retrieval",
  "explain_action",
  "explain_signal_score",
  "export_global_web_search_plan",
  "find_keyword_hits",
  "find_latest_compatible_manifest",
  "find_previous_successful_weekly_run",
  "get_v9_runs_dir",
  "integrate_multi_source_signals",
  "list_snapshots",
  "load_demo_signals",
  "load_demo_watch_profile",
  "load_email_delivery_config",
  "load_weekly_run_config",
  "load_global_web_country_profiles",
  "load_candidates_from_manifest",
  "load_paper_retrieval_artifact",
  "load_patent_retrieval_artifact",
  "load_retrieval_run_manifest",
  "load_signals_from_csv_text",
  "load_signals_from_json_text",
  "load_snapshot",
  "load_watch_profile",
  "load_web_company_retrieval_artifact",
  "migrate_watch_profile",
  "normalize_source_limits",
  "normalize_publication_number",
  "normalize_review_decision",
  "normalize_review_priority",
  "normalize_review_state",
  "normalize_total_limit",
  "normalize_terms",
  "normalize_signal_record",
  "normalize_signal_records",
  "parse_publication_numbers",
  "parse_terms",
  "prepare_uploaded_signals",
  "rank_integrated_signals",
  "release_weekly_run_lock",
  "resolve_project_path",
  "score_signal_with_profile",
  "select_diverse_top_signals",
  "save_digest_files",
  "save_email_delivery_log",
  "save_global_web_retrieval_artifacts",
  "save_openalex_paper_retrieval_artifacts",
  "sanitize_weekly_run_config",
  "save_patent_dry_run_artifacts",
  "save_patent_retrieval_artifacts",
  "save_retrieval_run_manifest",
  "save_snapshot",
  "save_watch_profile",
  "sort_signals_by_review",
  "signals_to_csv",
  "signals_to_json",
  "split_terms",
  "summarize_global_web_search_plan_ja",
  "summarize_search_plan_ja",
  "summarize_reviews",
  "run_patent_bigquery_dry_run",
  "run_email_delivery_dry_run",
  "run_weekly_watch",
  "send_digest_email_self_only",
  "stable_payload_signature",
  "acquire_weekly_run_lock",
  "validate_country_profiles",
  "validate_global_web_retrieval_request",
  "validate_openalex_request",
  "validate_global_web_search_plan",
  "validate_patent_bigquery_request",
  "validate_search_plan",
  "validate_self_only_delivery",
  "validate_weekly_run_config",
  "watch_profile_summary",
]


def __getattr__(name: str):
  module_path = _EXPORTS.get(name)
  if module_path is None:
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
  module = import_module(module_path, __name__)
  value = getattr(module, name)
  globals()[name] = value
  return value


def __dir__() -> list[str]:
  return sorted(set(list(globals()) + __all__))
